### ISSUE TITLE
Password reset - doesn't check if username/email exists

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#102]
Click "Forgot username or password" and then enter username or email address, it seems that the current platform doesn't check if the user name / email address exist. After entering a random username/invalid email address, the platform still shows "Done! a link....."

**Comment by sou-chon** [comment]
This is done to obscure outside people from keeping trying to see whether an email address / user exists.

That was before, when only admin could create a user. Now I guess people now can do the same with registration page.

But the server doesn't actually send any email or anything if the user doesn't exist, so no computation resource is used:

https://github.com/ideafast/ideafast-portal/blob/76641e49e75866b3acdfa2faf0d242ffa535a650/packages/itmat-interface/src/graphql/resolvers/userResolvers.ts#L119-L123


I would vote to keep it that way because i see many websites do it this way too

**Comment by fguitton** [comment]
As @sou-chon mentioned it is important that we don't permit an attacker to understand what email/username exist.
