### ISSUE TITLE
Sensitive information shown on the log details of 'LOGIN-USER' operation

### ISSUE THREAD

**Issue by kai87** [ideafast/ideafast-portal#316]
As the admin of the DMP, I am now able to see everyone's pwd and totp! 1) pwd shouldn't appear in the Details of LOGIN-USER; 2) should we encrypt the pwd when storing them in the dmp?

<img width="770" alt="Screen Shot 2020-11-27 at 15 58 08" src="https://user-images.githubusercontent.com/7723487/100467547-89e5d500-30ca-11eb-81ba-059a04029138.png">

**Comment by nguyentb** [comment]
@kai87  password is hashed and salted. We dont (never) store plain password at server. Only hash of the password is stored.
When checking password whether the user input is correct we just compare the hash.

This logging showing the plaintext of password is probably due to an implementation issue from @Siyao that he takes the password input from the client-side and directly store it onto log collection. Siyao needs to fix it ASAP.

**Comment by nguyentb** [comment]
@wsy19961129 fix it ASAP :dagger:
