### ISSUE TITLE
Load IDEA-FAST Feasibility Study successfully but log status is "FAIL"

### ISSUE THREAD

**Issue by GuanyuTao** [ideafast/ideafast-portal#397]
In the production environment, I can successfully load the page of IDEA-FAST Feasibility Study (https://data.ideafast.eu/datasets/7b6aac1c-366b-4259-ab05-9c6f47f956e5/files) and view the file list in this study, but the log status of this behaviour is "FAIL". 
![image](https://user-images.githubusercontent.com/9260585/107224829-dffebf00-6a0f-11eb-964c-08727a56b167.png)
All the log status of get IDEA-FAST Feasibility Study are "FAIL".  Only IDEA-FAST Feasibility Study has this issue, the other studies are fine. 
I am not sure if the DMP successfully return the correct information of this study or just a bug of the log mechanism.

**Comment by wsy19961129** [comment]
> In the production environment, I can successfully load the page of IDEA-FAST Feasibility Study (https://data.ideafast.eu/datasets/7b6aac1c-366b-4259-ab05-9c6f47f956e5/files) and view the file list in this study, but the log status of this behaviour is "FAIL".
> ![image](https://user-images.githubusercontent.com/9260585/107224829-dffebf00-6a0f-11eb-964c-08727a56b167.png)
> All the log status of get IDEA-FAST Feasibility Study are "FAIL". Only IDEA-FAST Feasibility Study has this issue, the other studies are fine.
> I am not sure if the DMP successfully return the correct information of this study or just a bug of the log mechanism.

The logger may have **different behaviour** as the frontend, because it only checks whether there is an _error_  field in the response. So if you check other logs, many of them are fail but does not influence the frontend, this is because graphql can still send data that are not influenced by the errors sometimes.

I checked the response and it says 'Cannot return null for null-able field File.hash', while I didn't find any file with no hash.

I think this question will need help from @fguitton as I am not certain how the hash is generated since the latest release.

**Comment by fguitton** [comment]
I could only generate the hashed for the files I have. Some records might be pointing out to deleted file not present in the object store and therefor these values aren't set. I can attempt to check whether these can be safely removed.
