### ISSUE TITLE
File search function error in some datasets

### ISSUE THREAD

**Issue by nguyentb** [ideafast/ideafast-portal#398]
Search function error in some datasets such as IDEA_TEST or Hackathon_test.
For instance, when typing the letter "i" in these datasets, the front-end shows nothing.
This error might be because of some invalid fields in some files in the datasets.

**Comment by wsy19961129** [comment]
I think this is because the value of fields in some files are **INVALID**, the easiest solution is to delete such files directly as they don't have meaningful contents.

I guess this is because at the moment of Hackathon, the validation of file name only happened on the frontend, so when the user tried to update via APIs, they could upload some illegal files. After the Hackathon, the validation is also performed on the backend so there would be no such errors again.
